### PR TITLE
Add Bazel build support for macOS

### PR DESCRIPTION
**Pull request by Vertexwahn**
This change request only affects the Bazel build. It contains

- Update of Bazel version to 5.0.0
- Fixes for Bazel build to support macOS

Resolves: https://github.com/oneapi-src/oneTBB/issues/723

### CODE REVIEW

**Comment by Vertexwahn** [comment]
@anton-potapov Maybe you can review it

**Comment by anton-potapov** [comment]
> @anton-potapov Maybe you can review it

I can but only English grammer :) 

@AlexVeprev could you please take a look ?

**Comment by AlexVeprev** [comment]
Technically LGTM, but @Vertexwahn please follow the contribution rule:

> git commit message contains appropriate signed-off-by string (see [CONTRIBUTING.md](https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md#pull-requests) for details)

**Comment by Vertexwahn** [comment]
@AlexVeprev I siggned-off the commits!

**Review by AlexVeprev — APPROVED** [review]

**Comment by AlexVeprev** [comment]
@Vertexwahn thank you for the contribution!

**Pull request merged**
