### PR TITLE
Cleanup .rc files

### PR DESCRIPTION
**Pull request by phprus**
### Description 
Warning list:

```
Build succeeded.

       "D:\a\oneTBB\oneTBB\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "D:\a\oneTBB\oneTBB\build\test\_test_malloc_atexit.vcxproj" (default target) (3) ->
       "D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj" (default target) (4) ->
       (ResourceCompile target) -> 
         D:\a\oneTBB\oneTBB\src\tbbmalloc\../../include/oneapi/tbb/detail/_config.h(285): warning RC4011: identifier truncated to '__ENVIRONMENT_IPHONE_OS_VERSION' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc\../../include/oneapi/tbb/detail/_config.h(377): warning RC4011: identifier truncated to 'TBB_PREVIEW_TASK_ARENA_CONSTRAI' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc\../../include/oneapi/tbb/detail/_config.h(405): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc\../../include/oneapi/tbb/detail/_config.h(405): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc\../../include/oneapi/tbb/detail/_config.h(426): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc\../../include/oneapi/tbb/detail/_config.h(426): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc\../../include/oneapi/tbb/detail/_config.h(434): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc\../../include/oneapi/tbb/detail/_config.h(434): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc\../../include/oneapi/tbb/detail/_config.h(519): warning RC4011: identifier truncated to 'TBB_PREVIEW_CONCURRENT_HASH_MAP' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc\../../include/oneapi/tbb/detail/_config.h(523): warning RC4011: identifier truncated to 'TBB_PREVIEW_TASK_GROUP_EXTENSIO' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc\tbbmalloc.rc(34): warning RC4005: 'ENDL' : redefinition [D:\a\oneTBB\oneTBB\build\src\tbbmalloc\tbbmalloc.vcxproj]


       "D:\a\oneTBB\oneTBB\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "D:\a\oneTBB\oneTBB\build\test\_test_malloc_atexit.vcxproj" (default target) (3) ->
       "D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj" (default target) (6) ->
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\../../include/oneapi/tbb/detail/_config.h(285): warning RC4011: identifier truncated to '__ENVIRONMENT_IPHONE_OS_VERSION' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\../../include/oneapi/tbb/detail/_config.h(377): warning RC4011: identifier truncated to 'TBB_PREVIEW_TASK_ARENA_CONSTRAI' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\../../include/oneapi/tbb/detail/_config.h(405): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\../../include/oneapi/tbb/detail/_config.h(405): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\../../include/oneapi/tbb/detail/_config.h(426): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\../../include/oneapi/tbb/detail/_config.h(426): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\../../include/oneapi/tbb/detail/_config.h(434): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\../../include/oneapi/tbb/detail/_config.h(434): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\../../include/oneapi/tbb/detail/_config.h(519): warning RC4011: identifier truncated to 'TBB_PREVIEW_CONCURRENT_HASH_MAP' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\../../include/oneapi/tbb/detail/_config.h(523): warning RC4011: identifier truncated to 'TBB_PREVIEW_TASK_GROUP_EXTENSIO' [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbbmalloc_proxy\tbbmalloc_proxy.rc(34): warning RC4005: 'ENDL' : redefinition [D:\a\oneTBB\oneTBB\build\src\tbbmalloc_proxy\tbbmalloc_proxy.vcxproj]


       "D:\a\oneTBB\oneTBB\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "D:\a\oneTBB\oneTBB\build\test\conformance_allocators.vcxproj" (default target) (8) ->
       "D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj" (default target) (9) ->
         D:\a\oneTBB\oneTBB\src\tbb\../../include/oneapi/tbb/detail/_config.h(285): warning RC4011: identifier truncated to '__ENVIRONMENT_IPHONE_OS_VERSION' [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbb\../../include/oneapi/tbb/detail/_config.h(377): warning RC4011: identifier truncated to 'TBB_PREVIEW_TASK_ARENA_CONSTRAI' [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbb\../../include/oneapi/tbb/detail/_config.h(405): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbb\../../include/oneapi/tbb/detail/_config.h(405): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbb\../../include/oneapi/tbb/detail/_config.h(426): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbb\../../include/oneapi/tbb/detail/_config.h(426): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbb\../../include/oneapi/tbb/detail/_config.h(434): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbb\../../include/oneapi/tbb/detail/_config.h(434): warning RC4011: identifier truncated to 'TBB_SUPPRESS_DEPRECATED_MESSAGE' [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbb\../../include/oneapi/tbb/detail/_config.h(519): warning RC4011: identifier truncated to 'TBB_PREVIEW_CONCURRENT_HASH_MAP' [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbb\../../include/oneapi/tbb/detail/_config.h(523): warning RC4011: identifier truncated to 'TBB_PREVIEW_TASK_GROUP_EXTENSIO' [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]
         D:\a\oneTBB\oneTBB\src\tbb\tbb.rc(34): warning RC4005: 'ENDL' : redefinition [D:\a\oneTBB\oneTBB\build\src\tbb\tbb.vcxproj]

    33 Warning(s)
    0 Error(s)
```

Fixes # - _issue number(s) if exists_

- [x] - git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md#pull-requests) for details)_

### Type of change

_Choose one or multiple, leave empty if none of the other choices apply_

_Add a respective label(s) to PR if you have permissions_

- [x] bug fix - _change that fixes an issue_
- [ ] new feature - _change that adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests

- [ ] added - _required for new features and some bug fixes_
- [x] not needed

### Documentation

- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [x] not needed

### Breaks backward compatibility
- [ ] Yes
- [x] No
- [ ] Unknown

### Notify the following users
@egfefey, @omalyshe

### CODE REVIEW

**Comment by egfefey** [comment]
All the warning messages are coming from tbb/detail/_config.h, which is included from version.h.
Since none of the macros referred to in the messages are used in the resource files, it should suffice to exclude only _config.h from the resource compiler with the RC_INVOKED macro. That should take care of the warnings.

For the redefinition, since ENDL is defined in version.h, removing it from the resource files should be fine once version.h is included. There's no need to disable it in version.h and leave the definition in the resource files.

At this point, I will hesitate to remove anything else that does not lead to a warning in the build as this is largely a re-introduced file from the old TBB until we're certain of why we no longer need them.

**Comment by omalyshe** [comment]
> At this point, I will hesitate to remove anything else that does not lead to a warning in the build as this is largely a re-introduced file from the old TBB until we're certain of why we no longer need them.

It looks like those macro are needed only for GUI applications (refer to [https://stackoverflow.com/questions/45284494/what-are-the-macros-in-resource-h-used-for](https://stackoverflow.com/questions/45284494/what-are-the-macros-in-resource-h-used-for) ), so unlikely relevant to TBB library. 
@egfefey Can you please check that with this patch the Property dialogs are correct for each DLL?

**Comment by phprus** [comment]
Rebased onto current master.

**Comment by pavelkumbrasev** [comment]
@egfefey Could you please take a look?

**Comment by phprus** [comment]
@pavelkumbrasev 

They are only needed when using the Visual Studio GUI-tools to edit resource files. Mainly for wizards to create a GUI.

https://stackoverflow.com/questions/45284494/what-are-the-macros-in-resource-h-used-for
https://learn.microsoft.com/en-us/cpp/mfc/tn035-using-multiple-resource-files-and-header-files-with-visual-cpp?redirectedfrom=MSDN&view=msvc-170

**Review by pavelkumbrasev — APPROVED** [review]

**Comment by pavelkumbrasev** [comment]
Could you please change the copyright year in those files?

**Comment by phprus** [comment]
@pavelkumbrasev 
Rebased and changed copyright year in files.

**Review by pavelkumbrasev — APPROVED** [review]

**Pull request merged**
