### PR TITLE
clang-tidy: use nullptr instead of NULL

### PR DESCRIPTION
**Pull request by isaevil**
### Description 
This patch applies clang-tidy check- `modernize-use-nullptr`

### Type of change

- [ ] bug fix - _change which fixes an issue_
- [ ] new feature - _change which adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests

- [ ] added - _required for new features and for some bug fixes_
- [x] not needed

### Documentation

- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [x] not needed

### Breaks backward compatibility
- [ ] Yes
- [x] No
- [ ] Unknown

### Notify the following users
@anton-potapov @vlserov @alexey-katranov

### CODE REVIEW

**Comment by anton-potapov** [comment]
@isaevil please update the patch to resolve the conflicts. 

overall, *LGTM*

**Review by anton-potapov — DISMISSED** [review]
*LGTM*

**Comment by isaevil** [comment]
@anton-potapov There was one more merge conflict? Could you reapprove please?

**Review by anton-potapov — APPROVED** [review]
*LGTM*

**Pull request merged**
