### PR TITLE
CMake: add option TBB_INSTALL

### PR DESCRIPTION
**Pull request by phprus**
Signed-off-by: Vladislav Shchapov <phprus@gmail.com>

### Description 
Make installation optional.

In the case of including oneTBB using add_subdirectory, it may require a custom installation rules.

Fixes # - _issue number(s) if exists_

- [x] - git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md#pull-requests) for details)_

### Type of change

_Choose one or multiple, leave empty if none of the other choices apply_

_Add a respective label(s) to PR if you have permissions_

- [ ] bug fix - _change that fixes an issue_
- [ ] new feature - _change that adds functionality_
- [ ] tests - _change in tests_
- [x] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests

- [ ] added - _required for new features and some bug fixes_
- [x] not needed

### Documentation

- [x] updated in this PR
- [ ] needs to be updated
- [ ] not needed

### Breaks backward compatibility
- [ ] Yes
- [x] No
- [ ] Unknown

### Notify the following users
_List users with `@` to send notifications_

### CODE REVIEW

**Comment by AlexVeprev** [comment]
Hi @phprus, I'd like to double check that I got the use case properly: you want to have oneTBB added into your project with `add_subdirectory` but don't want oneTBB to be installed when you run `make install` for your project. Right? And all you need - is to wrap all the installation instructions for oneTBB under condition with a new option TBB_INSTALL without other modifications of installation instructions. Right?

**Comment by phprus** [comment]
1) Yes;
2) Yes.

I use this patch (and set TBB_INSTALL to OFF) and custom ``install()`` commands (and some additional options for ``tbb*`` targets) for ``tbb``, ``tbbmalloc``, ``tbbmalloc_proxy`` targets in parent cmake project.

**Comment by phprus** [comment]
Ping?

**Comment by phprus** [comment]
Rebased

**Comment by phprus** [comment]
@pavelkumbrasev, @isaevil what do you think about this PR?

**Comment by phprus** [comment]
@pavelkumbrasev, @isaevil, @kboyarinov
ping?

**Comment by phprus** [comment]
Rebased

**Comment by phprus** [comment]
Rebased and ping.

**Comment by phprus** [comment]
Rebased to resolve conflicts with current master.

Request review @isaevil, @pavelkumbrasev, @dnmokhov, @ilya-lavrenov

**Comment by ilya-lavrenov** [comment]
@phprus can you just use `add_subdirectory` with `EXCLUDE_FROM_ALL` option? It will ignore TBB install rules.

**Comment by phprus** [comment]
@ilya-lavrenov, Thank you for your reply!

``EXCLUDE_FROM_ALL`` by default disables test compilation and does not allow to set custom installation rules for targets.

I need build/run all tests and ``install`` targets ``tbb``, ``tbbmalloc``, ``tbbmalloc_proxy`` with custom ``DESTINATION``s and ``COMPONENT``s options.

Since the build system has the ``TBB_INSTALL_VARS`` option, I suggest adding a option to completely disable the installation.

**Comment by ilya-lavrenov** [comment]
> EXCLUDE_FROM_ALL by default disables test compilation

Why do you need to build tests when TBB (or other external project) is used as submodule and included into main project via `add_subdirectory`? It's a good practice to include external projects with `EXCLUDE_FROM_ALL` option

> does not allow to set custom installation rules for targets

It allows. But there are some corner cases (like we had with pugixml https://github.com/zeux/pugixml/pull/585 in OpenVINO).
So, in general I agree that it's better to disable install rules.

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by phprus** [comment]
@ilya-lavrenov

> Why do you need to build tests when TBB (or other external project) is used as submodule and included into main project via ``add_subdirectory``?

We try to run tests for all dependencies. Sometimes this helps to find bugs in dependencies.

**Review by isaevil — APPROVED** [review]
LGTM

**Pull request merged**
