### PR TITLE
Add DLL info for all tbbbind versions instead of just the default

### PR DESCRIPTION
**Pull request by dnmokhov**
### Description 
_Add a comprehensive description of proposed changes_

Fixes # - _issue number(s) if exists_

- [x] - git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md#pull-requests) for details)_

### Type of change

_Choose one or multiple, leave empty if none of the other choices apply_

_Add a respective label(s) to PR if you have permissions_

- [x] bug fix - _change that fixes an issue_
- [ ] new feature - _change that adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests

- [ ] added - _required for new features and some bug fixes_
- [x] not needed

### Documentation

- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [x] not needed

### Breaks backward compatibility
- [ ] Yes
- [x] No
- [ ] Unknown

### Notify the following users
_List users with `@` to send notifications_

### CODE REVIEW

**Comment by dnmokhov** [comment]
### Example (was empty before)
after

**Comment by dnmokhov** [comment]
after

**Review by egfefey — COMMENTED** [review]
Can you also please post the shot for tbbbind version 2.5 as well?

**Comment by dnmokhov** [comment]
> Can you also please post the shot for tbbbind version 2.5 as well?

2.4 though, since this 2021.2 branch is pre-#448:
after

**Review by pavelkumbrasev — APPROVED** [review]

**Pull request merged**
